server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: app
          uri: http://localhost:8081
          predicates:
            - Path=/payments/**, /orders/**, /menus/**
        - id: store
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, /topMenus/**
        - id: kakao
          uri: http://localhost:8083
          predicates:
            - Path=/notificationLogs/**, /orderStates/**
        - id: delivery
          uri: http://localhost:8084
          predicates:
            - Path=/deliveItems/**, /checkItems/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: app
          uri: http://app:8080
          predicates:
            - Path=/payments/**, /orders/**, /menus/**
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/orders/**, /topMenus/**
        - id: kakao
          uri: http://kakao:8080
          predicates:
            - Path=/notificationLogs/**, /orderStates/**
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveItems/**, /checkItems/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
